version: '3'

services:
  php:
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/app_directory
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/app_directory
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
